site_name: DCAF
site_description: Informações úteis à Diretoria Central de Análise Fiscal.
site_url: https://exemplo.com

theme:
  name: material
  language: pt
  features:
    - navigation.expand
    - navigation.sections
    - navigation.top
    - navigation.tabs
    - search.highlight
    - search.share
    - content.code.copy
    - content.action.edit
    - content.tabs.link
    - content.tooltips
    - header.autohide
  palette:
    - scheme: slate  # modo escuro 
      primary: teal
      accent: lime
      toggle:
        icon: material/weather-sunny
        name: Mudar para modo claro
    - scheme: default  # modo claro 
      primary: teal
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Mudar para modo escuro
  font:
    text: "Inter"
    code: "JetBrains Mono"

# Logo e favicon opcionais
# logo: assets/logo.png
# favicon: assets/favicon.png

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - tables
  - toc:
      permalink: true
  - def_list
  - codehilite:
      guess_lang: false
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - social
  - tags
  - gemini-chatbot
  # - minify:  # opcional, melhora desempenho
  #     minify_html: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/splor-mg
  generator: false  # Remove o "Built with MkDocs" do rodapé
  analytics:
      provider: google
      property: G-9CQ61WJ7DC  # ID de medição do Google Analytics
    

nav:
  - Início: index.md
  - Sobre: sobre.md
  - Links: links.md
  - Manual: manual.md
  - Contatos: 
    - Contato DCAF: contato.md
    - Contatos Úteis: contuteis.md

extra_javascript:
  - js/chatbot.js
  - javascripts/extra.js


extra_css:
  - css/chatbot.css